server:
  port: 8100

# 日志配置
logging:
  config: classpath:log4j2.yml


spring:
  application:
    name: gk5-boot-sample-web
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 3000
