server:
  port: 8100

# 日志配置
logging:
  config: classpath:log4j2.yml


spring:
  application:
    name: gk5-boot-sample-web
  profiles:
    active: druid
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 3000

# MyBatis配置
mybatis:
  # Packages to search type aliases. (Package delimiters are ",; \t\n")
  typeAliasesPackage: wang.bannong.gk5.boot.sample.mybatis.entity
  # Locations of MyBatis mapper files.
  mapperLocations: classpath*:wang/bannong/gk5/boot/sample/mybatis/mapper/*Mapper.xml,classpath*:mapper/*Mapper.xml
  # Location of MyBatis xml config file.
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql