server:
  port: 8080
logging:
  config: classpath:log4j2.yml
spring:
  application:
    name: gk5-boot-sample-mybatis1ms

datasource:
  mappersPath: wang.bannong.gk5.boot.sample.mybatis1ms.mapper
  master:
    host: rm-m5eg91rzdb64901qazo.mysql.rds.aliyuncs.com
    port: 3306
    db: moguyunfu-stable
    username: mogucs
    password: Ty868pd1qasw2!@#
    maxIdle: 10
    minIdle: 5
    connectionTimeout: 30000
  slave:
    host: rm-m5eg91rzdb64901qazo.mysql.rds.aliyuncs.com
    port: 3306
    db: moguyunfu-stable
    username: mogucs
    password: Ty868pd1qasw2!@#
    maxIdle: 10
    minIdle: 5
    connectionTimeout: 30000
